
stages:
  - sanity_checks

check-dco:
  stage: sanity_checks
  needs: []
  image: registry.gitlab.com/libvirt/libvirt-ci/check-dco:master
  script:
    - /check-dco libvirt
  except:
    variables:
      - $CI_PROJECT_NAMESPACE == 'libvirt'
  variables:
    GIT_DEPTH: 1000
