---
- name: Create /usr/local/lib/systemd/system
  file:
    dest: "/usr/local/lib/systemd/system"
    state: directory

- name: Upload the boot notification service
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0755"
    force: yes
  loop:
    - { src: "{{ playbook_dir }}/files/call_home.service",
        dest: "/usr/local/lib/systemd/system" }
    - {
        src: "{{ playbook_dir }}/files/call_home.py",
        dest: "/opt/call_home.py" }
  notify:
    - reload-systemd
    - enable-call-home
