---
- name: Add gitlab-runner user
  user:
    name: gitlab-runner
    password: "!"
    state: present

- name: Allow passwordless sudo for the gitlab-runner user
  copy:
    dest: /etc/sudoers.d/gitlab-runner
    content: "gitlab-runner ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Upload SSH key for the gitlab-runner user
  authorized_key:
    user: gitlab-runner
    state: present
    key: "{{ lookup('file', '/opt/gitlab/id_ed25519.pub') }}"
